### ISSUE TITLE
Build frontend skeleton

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#2]
The bones of the frontend application are: 

- a branding bar
- a navigation bar to get from page to page (overview, sentencing, parole, etc)
- the pages to which one navigates

All of this should be more or less static at this point. Once it is in place we can start hanging more polished UI components from it.

**Questions**
- url-based routing? 
- should we be accounting for a multi-state website at this point?

**Comment by jessex** [comment]
1. URL-based routing seems right to me.
2. I wouldn't spend much effort _at all_ assuming multiple states yet. Though that's certainly the goal, what's more important is speed in this first launch. But I do think where this may be relevant now is, for example, prepending all URLs with a state-code (even if it's hard-coded to us_nd and the app just assumes us_nd for now) so that we can try to future-proof peoples' bookmarks going forward.
