### ISSUE TITLE
Handle "unknowns" consistently

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#330]
Occasionally, demographic breakdown metrics will include an "unknown" category with a few people who have, for whatever reason, not been properly classified. Because this is generally more indicative of a data issue than any real-world condition, we wound up excluding this category from most charts on the site, though some early ones (most notably the population section at the top of each page) included it for race and gender but not age, somewhat arbitrarily based on an early state of calc export data. This led to a lot of special case handling to exclude the unknown category in most places while also displaying it properly when it did appear.

The first pass at v2 reverses this, excluding the unknown category by default from all demographic breakdowns. This makes for simpler data handling in the majority of cases, but it does represent a methodological change from v1: "Unknown" no longer shows up in the aforementioned population charts, nor in the Sentence Types chart. (The data has not changed, only the application logic on the frontend.) The individuals contained in those unknowns are still counted toward totals, so astute readers may notice that the numbers do not add up. (This is especially noticeable in the Sentence Types section where the population per sentence type is prominently labeled.)

We need to evaluate: is this the behavior we want? 

- if yes, we probably want to note this in the relevant methodology copy. 
- if no, where do we want the unknowns to be displayed, if they are present? Because these places will presumably be in the minority, they should be handled as special cases to avoid all the other charts having to explicitly exclude unknowns.

**Comment by macfarlandian** [comment]
@hobuobi there's a product/methodology question here that we have to resolve before proceeding ... let me know if you want to discuss in more detail

**Comment by hobuobi** [comment]
A quick breakdown of a discussion between me, @macfarlandian , and @agr0n: 
There are two competing goals we probably want to be aware of: 
- **Representing the full population.** Ideally, the data that we show doesn't exclude anyone in the system. This could also be an issue if DOCs see that certain numbers don't line up with what they see in their systems. 
- **Clarity of communication.** As a public-facing tool, communicating clearly and concisely is important. At least in North Dakota, this Unknown issue is pretty rare -- definitely less than 1% of all people represented -- and thus it usually just results in a weird abberration rather than communicating any useful information. 

The solution we seem to have agreed on is to **1) exclude counts associated with Unknown values from the visualization,** and **2) include a note about this in the methodology.** Some additional things to keep in mind:
- The dataset that one can download should still have all the data (i.e. should still include the Unknown values).  
- An extension/enhancement of this would be to include a little tooltip whenever this happens to indicate that we excluded those data that amount to XX people, and that the full dataset should still include those folks. 
- We should probably keep track of the % of unknowns showing up in the data; if that % of Unknowns goes too high, it could possibly distort the results. This could be the case for other states (depending on data quality) or if there's some kind of data pipeline issue. @colincadams in case he has thoughts on this.
