### ISSUE TITLE
OG Image and Text

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#385]
We currently don't have an OG image or helpful text! See below. 
![image](https://user-images.githubusercontent.com/7134733/113337009-0a684c80-92dc-11eb-8e9a-08705932af10.png)

**Describe the solution you'd like**
OG Image should be the Spotlight logo on a green background: 
![og spotlight](https://user-images.githubusercontent.com/7134733/113337051-19e79580-92dc-11eb-9e86-4b10244eabce.png)

The accompanying text should be: 
"Explore correctional data in North Dakota. Developed by Recidiviz."

**Comment by macfarlandian** [comment]
looked into this a bit more - there is a complication in that these tags are static; we can't really tailor them to the particular page the user is looking at with our React application. In the short term that means we need the text to be more generic (because it won't always only be for North Dakota). If we were to add some kind of server-side rendering infrastructure in the future then we could accommodate making this feature more dynamic
