### ISSUE TITLE
[Spotlight] Look into bounce rate issue

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/public-dashboard#417]

**Comment by macfarlandian** [comment]
@hobuobi I spent a little time poking around in GA and I'm pretty sure this is a false alarm. If we want to get into specific figures, we should do it offline, but to summarize: 

- the big change in bounce rate coincides with the 2.0 release; any trend that crosses that boundary is suspect because there are lots of discontinuities that were introduced: the URLs changed, and even the way we are tracking pageviews changed, in a way that may have been artificially lowering the recorded bounce rate before 2.0. (I've added an annotation to the GA timeline to help us identify this boundary.)
- on both sides of the boundary, the bounce rate is very noisy. Traffic is low enough that I don't think this rate is a very meaningful signal on its own. That said, outside of the jump at release time it doesn't seem to be trending upwards in 2.0-land.
- We may have the opposite problem from before, where the bounce rate is artificially high because we haven't instrumented anything besides pageviews. If we were tracking, e.g., interactions with the filter or navigation UI elements, some proportion of those sessions wouldn't be considered bounces anymore.

It's not clear to me at this point that we have a well-founded target for what a "good" bounce rate would be for this site; in the absence of that I don't think this is really actionable for now?
