### ISSUE TITLE
Unknown numbers overflow bug

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#439]
Currently, our treatment for unknown values works fine for most graphs... but when there are many data points captured over time, the result can look a little clunky. This has become an issue with the Parole Population Over Time graph, where there are 1-3 individuals for which race/ethnicity is not known in many months in the 20 year period:

![image.png](https://images.zenhubusercontent.com/5efa0f1acabfc83e776b1102/4358cb0d-a02e-483b-9b1a-c5356214b590)

We need to figure out a more space-efficient solution for this. A few quick options to start: 
- Make the unknown numbers section collapsible -- small fixed height to start, then expands to reveal the full content. 
- Find a way to more compactly summarize the unknown values. 
- Suppress or shorten the unknown values disclaimer unless the missing values would cause an X% difference in the shown proportions in relevant breakdowns. 

Seeking thoughts from @macfarlandian in particular!

**Comment by macfarlandian** [comment]
making the text collapsible would be fairly straightforward. another similar option would be putting it in a modal rather than expanding it in place.

I am skeptical that we could really condense the text enough to satisfy situations like this, and personally I don't really like the idea of suppressing the values. We haven't really seen any cases yet where they are actually significant as a proportion of the total but still ... you shouldn't be forced to download the CSV to see that for yourself. 

This never really occurred to me before, but another idea is that, since we already detect the presence of unknowns, we could also just include them in the charts only when they are present, rather than making "unknown" a standing category everywhere? That might work better for some charts than others though (e.g. when there is one chart per category in the breakdown maybe we don't really want to add an extra one for "unknown"? or maybe that's fine?). Obviously this would be quite a bit more work but it would make for less clutter

**Comment by hobuobi** [comment]
Let's go with a collapsible solution for now! @agronomic or I can design something quick for this, or if you have a simple solution in mind, let us know and go for it!
