### ISSUE TITLE
Revamp Spotlight state landing page

### ISSUE THREAD

**Issue by jessex** [Recidiviz/public-dashboard#476]
**Is your feature request related to a problem? Please describe.**
The current Spotlight homepage - for both North Dakota and Pennsylvania - is very boring and leads to unacceptably high bounce rates. We want to reduce those bounce rates to ensure the app achieves its mission of increased transparency and information sharing.

**Describe the solution you'd like**
Update the Spotlight landing page ([current US_ND](https://dashboard.docr.nd.gov/us-nd), [current US_PA](https://dashboard.cor.pa.gov/us-pa)) to match what is described in the "Spotlight — Home Page Update" 1-pager and associated mocks. This includes:
- Updated top text styling and copy
- Display of charts directly on the landing page (these are all charts that are already displayed elsewhere in the app and simply need to be composed here, too)
- Testing across browsers and testing in mobile

**Describe alternatives you've considered**
N/A

**Additional context**
See the 1-pager and mocks for more details.

**Comment by cawarren** [comment]
Hey Ilya—one of our engineers mentioned that it may be difficult to get the North Dakota / Sentencing / Types of Sentences, by Age chart incorporated into the homepage, because it's a very complex and finicky chart.

If you find it's too complex to do easily, feel free to make the following changes instead:
Use 'Who is being sentenced' chart for 'Sentencing' instead:
https://dashboard.docr.nd.gov/us-nd/narratives/sentencing/2

If we make this change, for 'Parole', use the Free Through Recovery program chart instead of the one originally planned:
https://dashboard.docr.nd.gov/us-nd/narratives/parole/6

Lastly, if you decide to take this option (the two changes above, instead of the original 'Types of Sentences' chart), let us know and I'll provide updated copy / strings for those charts.

Thanks for your help on this!

**Comment by nasaownsky** [comment]
@cawarren Hi, Andrew! Yeah, this approach is much more easier to implement, and I already have more or less expected solution you can see below:

![screencapture-localhost-3000-us-nd-2021-08-24-20_02_16](https://user-images.githubusercontent.com/20225344/130660030-46665438-a21b-40c4-82a9-6b89f68815eb.png)

So only things I need to do is to get rid of Prison Population minimap and get new subtitles for updated charts.

**Comment by cawarren** [comment]
Amazing, thanks Ilya! Could you also make the map (lower-right) a little smaller? It feels kind of large given how far down it goes, below the chart to the left.

For the copy, you can use:

**Subtitle for Sentencing:** Demographics of Individuals Sentenced to Prison

**Subtitle for Parole:** 'Free Through Recovery' Program, Participants Statewide
