### ISSUE TITLE
Add older age buckets to Spotlight visualizations

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#479]
After expanding our dashboard to Pennsylvania, we have found that our original age breakdowns end up obscuring a lot of information about the age distributions; in particular, almost 50% of the Pennsylvania prison population is older than 40. 
The objective of this work item is to further break down the (older) age bracket available in the Spotlight dashboard. In particular, this will help us provide information to policymakers in Pennsylvania about the current and historical age breakdowns in the state, a crucial question relevant to the geriatric parole policy that is moving through the legislature. Carrying this change through all states and tenants on Spotlight will allow us to compare Pennsylvania's age breakdowns to those of other states as well. 

**The new age breakdowns should be:** 

- <25
- 25-29
- 30-39
- 40-49
- 50-59
- 60-69
- 70+

This change should affect all visualizations on the dashboard where an age breakdown currently exists, as well as all states/tenants on Spotlight.

**Comment by jessex** [comment]
I commented on the 1-pager for this that there is some amount of backend work that needs to happen before Ilya can proceed with the frontend, so this is currently blocked.

Once that's done, there will also be the need to produce updated data fixtures for all visualizations that match these new breakdowns. How does that process currently work, @macfarlandian?

**Comment by macfarlandian** [comment]
In the past I have just generated fixture files ad hoc with randomized values, so they're not necessarily consistent either internally or with one another — mostly optimizing for ease of generation since we don't have any particular tooling to lean on. I've either copied and edited exported files or just used a one-off Python session or something like that, depending on what I had to work with.

Because there is just one set of files that every tenant consumes in demo mode, one thing this does not lend itself well to is simulating cross-state differences — e.g. ND expecting a different set of race/ethnicity categories than PA. In the past I have either altered the files for local development to test that or generated additional files and swapped them out locally, but there are other solutions that could work also depending on what the data looks like. Of course if both states adopt the new categories then we won't really have to worry about it.

**Comment by colincadams** [comment]
The backend changes to allow us to set different age buckets per product have been landed for a while. The view change to use these new categories has not been made but should be quite trivial, see:
https://github.com/Recidiviz/recidiviz-data/blob/master/recidiviz/calculator/query/state/views/reference/single_day_incarceration_population_for_spotlight.py#L59
