### ISSUE TITLE
[Probation page] Success metrics section

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#54]
Basically Identical to corresponding section in Parole:
- filter the data source for probation rather than parole
- groupings are by Judicial District rather than parole office (labels should reflect this as needed)

**Comment by sprad** [comment]
@macfarlandian I started to work on this issue but realized that either I don't have the most up to date data files or that  our [success by month](https://github.com/Recidiviz/public-dashboard/blob/master/src/assets/test_data/US_ND_supervision_success_by_month.json#L2-L11) and [success by demographic](https://github.com/Recidiviz/public-dashboard/blob/master/src/assets/test_data/US_ND_supervision_success_by_period_by_demographics.json#L170-L181) data files don't map `PROBATION` records to a judicial district, but rather they seem to map to a parole office.  For example,

```json
  {
    "district": "1",
    "successful_termination_count": "173",
    "success_rate": "0.683794466403",
    "projected_completion_count": "253",
    "projected_month": "9",
    "projected_year": "2017",
    "supervision_type": "PROBATION",
    "state_code": "US_ND"
  },
```

Notice the `district` is identified by "1".  Compare this to a `PROBATION` record in the [population file](https://github.com/Recidiviz/public-dashboard/blob/master/src/assets/test_data/US_ND_supervision_population_by_district_by_demographics.json#L2225-L2233) where the `district` value maps to what we would expect for a judicial district key (i.e. "SOUTH_CENTRAL").

```json
  {
    "state_code": "US_ND",
    "district": "SOUTH_CENTRAL",
    "gender": "ALL",
    "age_bucket": "ALL",
    "race_or_ethnicity": "ALL",
    "total_supervision_count": 206,
    "supervision_type": "PROBATION"
  },
```

We can bring this up during today's standup if this issue is news to you.

**Comment by sprad** [comment]
I asked about this in stand up and @jjdressel11 told me that I'm working with old files and that she'll send me the updated files later today.

**Comment by macfarlandian** [comment]
yes good, i was about to comment to the same effect!
