### ISSUE TITLE
"Download Data" button

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#8]
detail pages have a "download data" button in the top bar. When clicked, this should bundle up all the data files used for visualizations into a zip file and download them.

**outstanding questions**
- what exactly should this bundle include? 
  - all the data for the current page
  - some subset of the data on the current page
  - all the data for all the pages
  - some subset of all the data for all the pages

**Comment by hobuobi** [comment]
Definitely just the data for that page, that's for sure. 
As far as "all data" vs "subset", I might need more info -- is there a sample of what the exported data would look like? 
Since I think we calculate all the metrics for the visualizations up front, I'm actually wondering how useful it would be to share the final metrics as opposed to the _actual_ raw data...

**Comment by macfarlandian** [comment]
what I had in mind was, for example, to plot district-level data on a map, in addition to the aggregate district-level data, we also use a second file that has all the district office locations, and possibly a third file for geographical stuff like county borders. Should we include all of that?

**Comment by hobuobi** [comment]
For that specifically, I would say we don't need to include the latter two levels -- just the aggregate district-level data would be fine. 
Basically all the demographic information should probably be included, as well as MoM stats when available in the visualizations... but I don't think we need to include things like specific geo information that would be necessary to fully recreate the visualization.
