### ISSUE TITLE
Dropdowns can overflow off small screens

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#91]
Dropdown menus are naively docked to the right edge of their trigger button and expand to the left. This is generally fine on desktop where the buttons are on the right, but on smaller screens they wrap to a separate line and align to the left:

![Screen Shot 2020-07-30 at 11 55 34 AM](https://user-images.githubusercontent.com/5385319/88962832-d8d64780-d25b-11ea-92b6-8a393d4705c1.png)

**Quick solution:** keep them always on the right and they should be fine for now!
**Robust solution:** implement some kind of "auto-placement" feature that keeps them in the viewport, or use a different dropdown library that does this natively.

**Comment by sprad** [comment]
I started to look into this, but I'm being called away so didn't get to a final solution.  The Quick solution can be implemented by [removing this line](https://github.com/Recidiviz/public-dashboard/blob/48ed7fe782f5a88752c2f50ee85d461b0804c26b/src/controls/Dropdown.js#L37) and all of the dropdowns on the details pages (Sentencing, Prison, Probation, Parole) look reasonable on desktop and mobile.  Unfortunately, this breaks the dropdowns on the Racial Disparity page because those dropdowns are right-aligned to the page and suffer from the opposite problem when this line is removed.
